name: TON Kurs

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  send-ton-price:
    runs-on: ubuntu-latest

    steps:
      - name: Kodni olish
        uses: actions/checkout@v4

      - name: Python o'rnatish
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Kutubxonalarni o'rnatish
        run: pip install -r requirements.txt

      - name: TON kursini yuborish
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python bot.py
